A Intuit sign-up website clone - Built with HTML & CSS
ghamtre/HTMLForms pull request #1
Opened 2020-02-21 18:05 UTC by ghamtre

We recreated the Intuit sign-up web page following the instructions required by [The Odin Project](https://www.theodinproject.com/courses/html5-and-css3/lessons/html-forms) and [Microverse Curriculum ](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/).

Any new changes will be documented and pushed on this pull request.

2020-02-21 23:09 UTC, pelzolga123 requested changes
Project requires changes.

2020-02-21 23:09 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing!

Here are changes you need to make before this project can be approved:
* [ ] The intuit logo should be an embedded image.([link to page](https://accounts.intuit.com/signup.html)) Right now you are adding it as a background, but you should add it as an `img`. 
* [ ] Product's row should contain 3 images (just like main logo above)  and text (logo on the left, text on the right).
* [ ] Your project is missing disclaimer text from original website, you can find it under phone input:
![image](https://user-images.githubusercontent.com/20416431/75077891-b9006200-550c-11ea-878d-eb0167178420.png)
* [ ] You need to have only one form in this project, no need to put each input in separate `form` tag.
I suggest for you to change `Forms` div to form and all forms you have inside to div's.
* [ ] Phone `<input>` should be of type `tel` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
* [ ] `Footbar` div should be inside a footer tag, or just change div to footer.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-02-24 17:53 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team,  You have done a great job with this project. :clap:, but there is just one more thing you need to change, check inline comments.

2020-02-24 17:54 UTC, kobiyoyo commented on index.html
> +                              <p>Standard call, messaging or data rates may apply.</p>
This should be under Phone input not password

2020-02-24 19:05 UTC, merged